/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AIAnalysis {
  'id' : AnalysisId,
  'completedAt' : Timestamp,
  'suggestions' : Array<string>,
  'thinking' : string,
  'target' : string,
  'vulnerabilities' : Array<AIVulnerability>,
  'riskScore' : bigint,
}
export type AIAnalysisResult = { 'ok' : AIAnalysis } |
  { 'err' : string };
export interface AIVulnerability {
  'title' : string,
  'description' : string,
  'severity' : string,
  'recommendation' : string,
}
export interface APIStatus {
  'status' : string,
  'name' : string,
  'lastChecked' : Timestamp,
  'responseTime' : bigint,
}
export interface ActivityEntry {
  'id' : ActivityId,
  'message' : string,
  'timestamp' : Timestamp,
  'severity' : string,
  'eventType' : ActivityEventType,
}
export type ActivityEventType = { 'ScanComplete' : null } |
  { 'VulnFound' : null } |
  { 'ThreatDetected' : null } |
  { 'APIHit' : null } |
  { 'ScanStarted' : null };
export type ActivityId = bigint;
export type AnalysisId = bigint;
export interface ContactSubmission {
  'id' : SubmissionId,
  'name' : string,
  'submittedAt' : Timestamp,
  'email' : string,
  'company' : string,
  'message' : string,
}
export type CreateScanResult = { 'ok' : Scan } |
  { 'err' : string };
export interface Finding {
  'id' : bigint,
  'protocol' : [] | [string],
  'title' : string,
  'port' : [] | [bigint],
  'description' : string,
  'cvssScore' : number,
  'severity' : string,
  'findingType' : string,
}
export interface Scan {
  'id' : ScanId,
  'status' : string,
  'completedAt' : [] | [Timestamp],
  'startedAt' : Timestamp,
  'mode' : string,
  'progress' : bigint,
  'target' : string,
  'findings' : Array<Finding>,
}
export type ScanId = bigint;
export type SubmissionId = bigint;
export interface SubmitContactInput {
  'name' : string,
  'email' : string,
  'company' : string,
  'message' : string,
}
export type SubmitContactResult = { 'ok' : SubmissionId } |
  { 'err' : string };
export interface SystemStatus {
  'aiEngineStatus' : string,
  'securityScore' : bigint,
  'apiStatuses' : Array<APIStatus>,
  'queueSize' : bigint,
  'activeScans' : bigint,
}
export interface ThreatEntry {
  'id' : ThreatId,
  'source' : string,
  'detectedAt' : Timestamp,
  'description' : string,
  'indicatorType' : string,
  'indicator' : string,
  'riskLevel' : string,
}
export interface ThreatEntryInput {
  'source' : string,
  'description' : string,
  'indicatorType' : string,
  'indicator' : string,
  'riskLevel' : string,
}
export type ThreatId = bigint;
export interface ThreatResult {
  'found' : boolean,
  'entry' : [] | [ThreatEntry],
  'relatedThreats' : Array<ThreatEntry>,
}
export type Timestamp = bigint;
export interface _SERVICE {
  'addActivity' : ActorMethod<
    [ActivityEventType, string, string],
    ActivityEntry
  >,
  'addThreatEntry' : ActorMethod<[ThreatEntryInput], ThreatEntry>,
  'analyzeTarget' : ActorMethod<[string, string], AIAnalysisResult>,
  'createScan' : ActorMethod<[string, string], CreateScanResult>,
  'getAnalysis' : ActorMethod<[AnalysisId], [] | [AIAnalysis]>,
  'getScan' : ActorMethod<[ScanId], [] | [Scan]>,
  'getSystemStatus' : ActorMethod<[], SystemStatus>,
  'listActivities' : ActorMethod<[bigint], Array<ActivityEntry>>,
  'listAnalyses' : ActorMethod<[], Array<AIAnalysis>>,
  'listContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'listScans' : ActorMethod<[], Array<Scan>>,
  'listThreats' : ActorMethod<[], Array<ThreatEntry>>,
  'lookupThreat' : ActorMethod<[string, string], ThreatResult>,
  'submitContact' : ActorMethod<[SubmitContactInput], SubmitContactResult>,
  'updateScanStatus' : ActorMethod<[ScanId, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];