/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ActivityEventType = IDL.Variant({
  'ScanComplete' : IDL.Null,
  'VulnFound' : IDL.Null,
  'ThreatDetected' : IDL.Null,
  'APIHit' : IDL.Null,
  'ScanStarted' : IDL.Null,
});
export const ActivityId = IDL.Nat;
export const Timestamp = IDL.Int;
export const ActivityEntry = IDL.Record({
  'id' : ActivityId,
  'message' : IDL.Text,
  'timestamp' : Timestamp,
  'severity' : IDL.Text,
  'eventType' : ActivityEventType,
});
export const ThreatEntryInput = IDL.Record({
  'source' : IDL.Text,
  'description' : IDL.Text,
  'indicatorType' : IDL.Text,
  'indicator' : IDL.Text,
  'riskLevel' : IDL.Text,
});
export const ThreatId = IDL.Nat;
export const ThreatEntry = IDL.Record({
  'id' : ThreatId,
  'source' : IDL.Text,
  'detectedAt' : Timestamp,
  'description' : IDL.Text,
  'indicatorType' : IDL.Text,
  'indicator' : IDL.Text,
  'riskLevel' : IDL.Text,
});
export const AnalysisId = IDL.Nat;
export const AIVulnerability = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'severity' : IDL.Text,
  'recommendation' : IDL.Text,
});
export const AIAnalysis = IDL.Record({
  'id' : AnalysisId,
  'completedAt' : Timestamp,
  'suggestions' : IDL.Vec(IDL.Text),
  'thinking' : IDL.Text,
  'target' : IDL.Text,
  'vulnerabilities' : IDL.Vec(AIVulnerability),
  'riskScore' : IDL.Nat,
});
export const AIAnalysisResult = IDL.Variant({
  'ok' : AIAnalysis,
  'err' : IDL.Text,
});
export const ScanId = IDL.Nat;
export const Finding = IDL.Record({
  'id' : IDL.Nat,
  'protocol' : IDL.Opt(IDL.Text),
  'title' : IDL.Text,
  'port' : IDL.Opt(IDL.Nat),
  'description' : IDL.Text,
  'cvssScore' : IDL.Float64,
  'severity' : IDL.Text,
  'findingType' : IDL.Text,
});
export const Scan = IDL.Record({
  'id' : ScanId,
  'status' : IDL.Text,
  'completedAt' : IDL.Opt(Timestamp),
  'startedAt' : Timestamp,
  'mode' : IDL.Text,
  'progress' : IDL.Nat,
  'target' : IDL.Text,
  'findings' : IDL.Vec(Finding),
});
export const CreateScanResult = IDL.Variant({ 'ok' : Scan, 'err' : IDL.Text });
export const APIStatus = IDL.Record({
  'status' : IDL.Text,
  'name' : IDL.Text,
  'lastChecked' : Timestamp,
  'responseTime' : IDL.Nat,
});
export const SystemStatus = IDL.Record({
  'aiEngineStatus' : IDL.Text,
  'securityScore' : IDL.Nat,
  'apiStatuses' : IDL.Vec(APIStatus),
  'queueSize' : IDL.Nat,
  'activeScans' : IDL.Nat,
});
export const SubmissionId = IDL.Nat;
export const ContactSubmission = IDL.Record({
  'id' : SubmissionId,
  'name' : IDL.Text,
  'submittedAt' : Timestamp,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'message' : IDL.Text,
});
export const ThreatResult = IDL.Record({
  'found' : IDL.Bool,
  'entry' : IDL.Opt(ThreatEntry),
  'relatedThreats' : IDL.Vec(ThreatEntry),
});
export const SubmitContactInput = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'message' : IDL.Text,
});
export const SubmitContactResult = IDL.Variant({
  'ok' : SubmissionId,
  'err' : IDL.Text,
});

export const idlService = IDL.Service({
  'addActivity' : IDL.Func(
      [ActivityEventType, IDL.Text, IDL.Text],
      [ActivityEntry],
      [],
    ),
  'addThreatEntry' : IDL.Func([ThreatEntryInput], [ThreatEntry], []),
  'analyzeTarget' : IDL.Func([IDL.Text, IDL.Text], [AIAnalysisResult], []),
  'createScan' : IDL.Func([IDL.Text, IDL.Text], [CreateScanResult], []),
  'getAnalysis' : IDL.Func([AnalysisId], [IDL.Opt(AIAnalysis)], ['query']),
  'getScan' : IDL.Func([ScanId], [IDL.Opt(Scan)], ['query']),
  'getSystemStatus' : IDL.Func([], [SystemStatus], ['query']),
  'listActivities' : IDL.Func([IDL.Nat], [IDL.Vec(ActivityEntry)], ['query']),
  'listAnalyses' : IDL.Func([], [IDL.Vec(AIAnalysis)], ['query']),
  'listContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'listScans' : IDL.Func([], [IDL.Vec(Scan)], ['query']),
  'listThreats' : IDL.Func([], [IDL.Vec(ThreatEntry)], ['query']),
  'lookupThreat' : IDL.Func([IDL.Text, IDL.Text], [ThreatResult], ['query']),
  'submitContact' : IDL.Func([SubmitContactInput], [SubmitContactResult], []),
  'updateScanStatus' : IDL.Func([ScanId, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ActivityEventType = IDL.Variant({
    'ScanComplete' : IDL.Null,
    'VulnFound' : IDL.Null,
    'ThreatDetected' : IDL.Null,
    'APIHit' : IDL.Null,
    'ScanStarted' : IDL.Null,
  });
  const ActivityId = IDL.Nat;
  const Timestamp = IDL.Int;
  const ActivityEntry = IDL.Record({
    'id' : ActivityId,
    'message' : IDL.Text,
    'timestamp' : Timestamp,
    'severity' : IDL.Text,
    'eventType' : ActivityEventType,
  });
  const ThreatEntryInput = IDL.Record({
    'source' : IDL.Text,
    'description' : IDL.Text,
    'indicatorType' : IDL.Text,
    'indicator' : IDL.Text,
    'riskLevel' : IDL.Text,
  });
  const ThreatId = IDL.Nat;
  const ThreatEntry = IDL.Record({
    'id' : ThreatId,
    'source' : IDL.Text,
    'detectedAt' : Timestamp,
    'description' : IDL.Text,
    'indicatorType' : IDL.Text,
    'indicator' : IDL.Text,
    'riskLevel' : IDL.Text,
  });
  const AnalysisId = IDL.Nat;
  const AIVulnerability = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'severity' : IDL.Text,
    'recommendation' : IDL.Text,
  });
  const AIAnalysis = IDL.Record({
    'id' : AnalysisId,
    'completedAt' : Timestamp,
    'suggestions' : IDL.Vec(IDL.Text),
    'thinking' : IDL.Text,
    'target' : IDL.Text,
    'vulnerabilities' : IDL.Vec(AIVulnerability),
    'riskScore' : IDL.Nat,
  });
  const AIAnalysisResult = IDL.Variant({ 'ok' : AIAnalysis, 'err' : IDL.Text });
  const ScanId = IDL.Nat;
  const Finding = IDL.Record({
    'id' : IDL.Nat,
    'protocol' : IDL.Opt(IDL.Text),
    'title' : IDL.Text,
    'port' : IDL.Opt(IDL.Nat),
    'description' : IDL.Text,
    'cvssScore' : IDL.Float64,
    'severity' : IDL.Text,
    'findingType' : IDL.Text,
  });
  const Scan = IDL.Record({
    'id' : ScanId,
    'status' : IDL.Text,
    'completedAt' : IDL.Opt(Timestamp),
    'startedAt' : Timestamp,
    'mode' : IDL.Text,
    'progress' : IDL.Nat,
    'target' : IDL.Text,
    'findings' : IDL.Vec(Finding),
  });
  const CreateScanResult = IDL.Variant({ 'ok' : Scan, 'err' : IDL.Text });
  const APIStatus = IDL.Record({
    'status' : IDL.Text,
    'name' : IDL.Text,
    'lastChecked' : Timestamp,
    'responseTime' : IDL.Nat,
  });
  const SystemStatus = IDL.Record({
    'aiEngineStatus' : IDL.Text,
    'securityScore' : IDL.Nat,
    'apiStatuses' : IDL.Vec(APIStatus),
    'queueSize' : IDL.Nat,
    'activeScans' : IDL.Nat,
  });
  const SubmissionId = IDL.Nat;
  const ContactSubmission = IDL.Record({
    'id' : SubmissionId,
    'name' : IDL.Text,
    'submittedAt' : Timestamp,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'message' : IDL.Text,
  });
  const ThreatResult = IDL.Record({
    'found' : IDL.Bool,
    'entry' : IDL.Opt(ThreatEntry),
    'relatedThreats' : IDL.Vec(ThreatEntry),
  });
  const SubmitContactInput = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'message' : IDL.Text,
  });
  const SubmitContactResult = IDL.Variant({
    'ok' : SubmissionId,
    'err' : IDL.Text,
  });
  
  return IDL.Service({
    'addActivity' : IDL.Func(
        [ActivityEventType, IDL.Text, IDL.Text],
        [ActivityEntry],
        [],
      ),
    'addThreatEntry' : IDL.Func([ThreatEntryInput], [ThreatEntry], []),
    'analyzeTarget' : IDL.Func([IDL.Text, IDL.Text], [AIAnalysisResult], []),
    'createScan' : IDL.Func([IDL.Text, IDL.Text], [CreateScanResult], []),
    'getAnalysis' : IDL.Func([AnalysisId], [IDL.Opt(AIAnalysis)], ['query']),
    'getScan' : IDL.Func([ScanId], [IDL.Opt(Scan)], ['query']),
    'getSystemStatus' : IDL.Func([], [SystemStatus], ['query']),
    'listActivities' : IDL.Func([IDL.Nat], [IDL.Vec(ActivityEntry)], ['query']),
    'listAnalyses' : IDL.Func([], [IDL.Vec(AIAnalysis)], ['query']),
    'listContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'listScans' : IDL.Func([], [IDL.Vec(Scan)], ['query']),
    'listThreats' : IDL.Func([], [IDL.Vec(ThreatEntry)], ['query']),
    'lookupThreat' : IDL.Func([IDL.Text, IDL.Text], [ThreatResult], ['query']),
    'submitContact' : IDL.Func([SubmitContactInput], [SubmitContactResult], []),
    'updateScanStatus' : IDL.Func([ScanId, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };