/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type CreateScanResult = {
    __kind__: "ok";
    ok: Scan;
} | {
    __kind__: "err";
    err: string;
};
export type Timestamp = bigint;
export interface AIVulnerability {
    title: string;
    description: string;
    severity: string;
    recommendation: string;
}
export interface ContactSubmission {
    id: SubmissionId;
    name: string;
    submittedAt: Timestamp;
    email: string;
    company: string;
    message: string;
}
export type SubmitContactResult = {
    __kind__: "ok";
    ok: SubmissionId;
} | {
    __kind__: "err";
    err: string;
};
export interface ThreatEntry {
    id: ThreatId;
    source: string;
    detectedAt: Timestamp;
    description: string;
    indicatorType: string;
    indicator: string;
    riskLevel: string;
}
export interface Scan {
    id: ScanId;
    status: string;
    completedAt?: Timestamp;
    startedAt: Timestamp;
    mode: string;
    progress: bigint;
    target: string;
    findings: Array<Finding>;
}
export interface ThreatResult {
    found: boolean;
    entry?: ThreatEntry;
    relatedThreats: Array<ThreatEntry>;
}
export interface APIStatus {
    status: string;
    name: string;
    lastChecked: Timestamp;
    responseTime: bigint;
}
export interface AIAnalysis {
    id: AnalysisId;
    completedAt: Timestamp;
    suggestions: Array<string>;
    thinking: string;
    target: string;
    vulnerabilities: Array<AIVulnerability>;
    riskScore: bigint;
}
export type SubmissionId = bigint;
export type AIAnalysisResult = {
    __kind__: "ok";
    ok: AIAnalysis;
} | {
    __kind__: "err";
    err: string;
};
export type ScanId = bigint;
export type ActivityId = bigint;
export type AnalysisId = bigint;
export type ThreatId = bigint;
export interface Finding {
    id: bigint;
    protocol?: string;
    title: string;
    port?: bigint;
    description: string;
    cvssScore: number;
    severity: string;
    findingType: string;
}
export interface ThreatEntryInput {
    source: string;
    description: string;
    indicatorType: string;
    indicator: string;
    riskLevel: string;
}
export interface ActivityEntry {
    id: ActivityId;
    message: string;
    timestamp: Timestamp;
    severity: string;
    eventType: ActivityEventType;
}
export interface SubmitContactInput {
    name: string;
    email: string;
    company: string;
    message: string;
}
export interface SystemStatus {
    aiEngineStatus: string;
    securityScore: bigint;
    apiStatuses: Array<APIStatus>;
    queueSize: bigint;
    activeScans: bigint;
}
export enum ActivityEventType {
    ScanComplete = "ScanComplete",
    VulnFound = "VulnFound",
    ThreatDetected = "ThreatDetected",
    APIHit = "APIHit",
    ScanStarted = "ScanStarted"
}
export interface backendInterface {
    addActivity(eventType: ActivityEventType, message: string, severity: string): Promise<ActivityEntry>;
    addThreatEntry(entry: ThreatEntryInput): Promise<ThreatEntry>;
    analyzeTarget(target: string, context: string): Promise<AIAnalysisResult>;
    createScan(target: string, scanMode: string): Promise<CreateScanResult>;
    getAnalysis(id: AnalysisId): Promise<AIAnalysis | null>;
    getScan(id: ScanId): Promise<Scan | null>;
    getSystemStatus(): Promise<SystemStatus>;
    listActivities(limit: bigint): Promise<Array<ActivityEntry>>;
    listAnalyses(): Promise<Array<AIAnalysis>>;
    listContactSubmissions(): Promise<Array<ContactSubmission>>;
    listScans(): Promise<Array<Scan>>;
    listThreats(): Promise<Array<ThreatEntry>>;
    lookupThreat(indicator: string, indicatorType: string): Promise<ThreatResult>;
    submitContact(input: SubmitContactInput): Promise<SubmitContactResult>;
    updateScanStatus(id: ScanId, status: string): Promise<boolean>;
}
import type { AIAnalysis as _AIAnalysis, AIAnalysisResult as _AIAnalysisResult, ActivityEntry as _ActivityEntry, ActivityEventType as _ActivityEventType, ActivityId as _ActivityId, CreateScanResult as _CreateScanResult, Finding as _Finding, Scan as _Scan, ScanId as _ScanId, SubmissionId as _SubmissionId, SubmitContactResult as _SubmitContactResult, ThreatEntry as _ThreatEntry, ThreatResult as _ThreatResult, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addActivity(arg0: ActivityEventType, arg1: string, arg2: string): Promise<ActivityEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.addActivity(to_candid_ActivityEventType_n1(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return from_candid_ActivityEntry_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addActivity(to_candid_ActivityEventType_n1(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return from_candid_ActivityEntry_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async addThreatEntry(arg0: ThreatEntryInput): Promise<ThreatEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.addThreatEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addThreatEntry(arg0);
            return result;
        }
    }
    async analyzeTarget(arg0: string, arg1: string): Promise<AIAnalysisResult> {
        if (this.processError) {
            try {
                const result = await this.actor.analyzeTarget(arg0, arg1);
                return from_candid_AIAnalysisResult_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.analyzeTarget(arg0, arg1);
            return from_candid_AIAnalysisResult_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async createScan(arg0: string, arg1: string): Promise<CreateScanResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createScan(arg0, arg1);
                return from_candid_CreateScanResult_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createScan(arg0, arg1);
            return from_candid_CreateScanResult_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnalysis(arg0: AnalysisId): Promise<AIAnalysis | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalysis(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalysis(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getScan(arg0: ScanId): Promise<Scan | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getScan(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScan(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSystemStatus(): Promise<SystemStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getSystemStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSystemStatus();
            return result;
        }
    }
    async listActivities(arg0: bigint): Promise<Array<ActivityEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.listActivities(arg0);
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listActivities(arg0);
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAnalyses(): Promise<Array<AIAnalysis>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAnalyses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAnalyses();
            return result;
        }
    }
    async listContactSubmissions(): Promise<Array<ContactSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.listContactSubmissions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listContactSubmissions();
            return result;
        }
    }
    async listScans(): Promise<Array<Scan>> {
        if (this.processError) {
            try {
                const result = await this.actor.listScans();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listScans();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async listThreats(): Promise<Array<ThreatEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.listThreats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listThreats();
            return result;
        }
    }
    async lookupThreat(arg0: string, arg1: string): Promise<ThreatResult> {
        if (this.processError) {
            try {
                const result = await this.actor.lookupThreat(arg0, arg1);
                return from_candid_ThreatResult_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.lookupThreat(arg0, arg1);
            return from_candid_ThreatResult_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitContact(arg0: SubmitContactInput): Promise<SubmitContactResult> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContact(arg0);
                return from_candid_SubmitContactResult_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContact(arg0);
            return from_candid_SubmitContactResult_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateScanStatus(arg0: ScanId, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateScanStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateScanStatus(arg0, arg1);
            return result;
        }
    }
}
function from_candid_AIAnalysisResult_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AIAnalysisResult): AIAnalysisResult {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_ActivityEntry_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityEntry): ActivityEntry {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_ActivityEventType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityEventType): ActivityEventType {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_CreateScanResult_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CreateScanResult): CreateScanResult {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Finding_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Finding): Finding {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Scan_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Scan): Scan {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_SubmitContactResult_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubmitContactResult): SubmitContactResult {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_ThreatResult_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ThreatResult): ThreatResult {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AIAnalysis]): AIAnalysis | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Scan]): Scan | null {
    return value.length === 0 ? null : from_candid_Scan_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ThreatEntry]): ThreatEntry | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ScanId;
    status: string;
    completedAt: [] | [_Timestamp];
    startedAt: _Timestamp;
    mode: string;
    progress: bigint;
    target: string;
    findings: Array<_Finding>;
}): {
    id: ScanId;
    status: string;
    completedAt?: Timestamp;
    startedAt: Timestamp;
    mode: string;
    progress: bigint;
    target: string;
    findings: Array<Finding>;
} {
    return {
        id: value.id,
        status: value.status,
        completedAt: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.completedAt)),
        startedAt: value.startedAt,
        mode: value.mode,
        progress: value.progress,
        target: value.target,
        findings: from_candid_vec_n14(_uploadFile, _downloadFile, value.findings)
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    protocol: [] | [string];
    title: string;
    port: [] | [bigint];
    description: string;
    cvssScore: number;
    severity: string;
    findingType: string;
}): {
    id: bigint;
    protocol?: string;
    title: string;
    port?: bigint;
    description: string;
    cvssScore: number;
    severity: string;
    findingType: string;
} {
    return {
        id: value.id,
        protocol: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.protocol)),
        title: value.title,
        port: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.port)),
        description: value.description,
        cvssScore: value.cvssScore,
        severity: value.severity,
        findingType: value.findingType
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    found: boolean;
    entry: [] | [_ThreatEntry];
    relatedThreats: Array<_ThreatEntry>;
}): {
    found: boolean;
    entry?: ThreatEntry;
    relatedThreats: Array<ThreatEntry>;
} {
    return {
        found: value.found,
        entry: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.entry)),
        relatedThreats: value.relatedThreats
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ActivityId;
    message: string;
    timestamp: _Timestamp;
    severity: string;
    eventType: _ActivityEventType;
}): {
    id: ActivityId;
    message: string;
    timestamp: Timestamp;
    severity: string;
    eventType: ActivityEventType;
} {
    return {
        id: value.id,
        message: value.message,
        timestamp: value.timestamp,
        severity: value.severity,
        eventType: from_candid_ActivityEventType_n5(_uploadFile, _downloadFile, value.eventType)
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Scan;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Scan;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Scan_n11(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _SubmissionId;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: SubmissionId;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ScanComplete: null;
} | {
    VulnFound: null;
} | {
    ThreatDetected: null;
} | {
    APIHit: null;
} | {
    ScanStarted: null;
}): ActivityEventType {
    return "ScanComplete" in value ? ActivityEventType.ScanComplete : "VulnFound" in value ? ActivityEventType.VulnFound : "ThreatDetected" in value ? ActivityEventType.ThreatDetected : "APIHit" in value ? ActivityEventType.APIHit : "ScanStarted" in value ? ActivityEventType.ScanStarted : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _AIAnalysis;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: AIAnalysis;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Finding>): Array<Finding> {
    return value.map((x)=>from_candid_Finding_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ActivityEntry>): Array<ActivityEntry> {
    return value.map((x)=>from_candid_ActivityEntry_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Scan>): Array<Scan> {
    return value.map((x)=>from_candid_Scan_n11(_uploadFile, _downloadFile, x));
}
function to_candid_ActivityEventType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityEventType): _ActivityEventType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityEventType): {
    ScanComplete: null;
} | {
    VulnFound: null;
} | {
    ThreatDetected: null;
} | {
    APIHit: null;
} | {
    ScanStarted: null;
} {
    return value == ActivityEventType.ScanComplete ? {
        ScanComplete: null
    } : value == ActivityEventType.VulnFound ? {
        VulnFound: null
    } : value == ActivityEventType.ThreatDetected ? {
        ThreatDetected: null
    } : value == ActivityEventType.APIHit ? {
        APIHit: null
    } : value == ActivityEventType.ScanStarted ? {
        ScanStarted: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
